kind: Template
apiVersion: v1
template: wine-data-loader
metadata:
  name: wine-data-loader
objects:

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      host: ${APP_NAME}-${PROJECT_NAME}.${HOST}${SUFFIX}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${APP_NAME}

  - apiVersion: v1
    kind: Secret
    metadata:
      name: winemap-secret
      namespace: winemap-namespace
    data:
      username: dXNlcm5hbWU=
      password: cGFzc3dvcmQ=
      server: cG9zdGdyZXNxbA==
      dbname: d2luZURi

  - kind: Job
    apiVersion: batch/v1
    metadata:
      name: ${JOB_NAME}
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: ${JOB_NAME}
        spec:
          containers:
            - name: wine-data-loader
              image: docker.io/radanalyticsio/winemap-data-loader
              env:
                - name: SERVER
                  valueFrom:
                    secretKeyRef:
                      name: winemap-secret
                      key: server
                - name: DBNAME
                  valueFrom:
                    secretKeyRef:
                      name: winemap-secret
                      key: dbname
                - name: USER
                  valueFrom:
                    secretKeyRef:
                      name: winemap-secret
                      key: username
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: winemap-secret
                      key: password
          restartPolicy: OnFailure

parameters:
  - name: JOB_NAME
    from: "jdsl-[a-z0-9]{4}"
    generate: expression
    description: unique name for this job run
  - name: APP_NAME
    required: true
  - name: PROJECT_NAME
    description: "The project namespace."
    required: true
  - name: HOST
    required: true
  - name: SUFFIX
    required: true

